version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_WITHOUT: development
    volumes:
      - .:/rails
    command: "./bin/rails server"
